### ISSUE TITLE
add option to return result instead of printing it

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#11]
as we are creating a package, maybe our users will need to use it not to merely print the results of their research but instead to store the information somewhere for further use. that's why I would like to add an optiona argument to request something like "return result" instead of "print (result)" and make it work with the verbosity argument as well.

**Comment by Leonardfonz** [comment]
Solved in eb227de
I added the add_argument line in the userapp.py file.
I modified checks.py and added if-else to make use of the new argument
