### ISSUE TITLE
add possibility to use different csv file

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#12]
as our package already works with a .csv file, it would be an easy yet good improvement to give the user the possibility to choose another csv file so the package can be expanded to include capitals and countries also outside of EU

**Comment by AdaMalve** [comment]
solved in c98811eeabf93339d4748814a3fa8cd078f454e3
first, I create a csvtest inside /capitals; I modify userapp.py and add optional argument --choosecsv. I also modify outputs of checks
