### ISSUE TITLE
develop helper code to create a database

### ISSUE THREAD

**Issue by saraweatherley** [massimodalmonico/capitals#15]
create a file /scripts/dbmanager.py which does the following tasks:

- [x] check if a database in a specific file path exists
- [x] if not, create one with a given schema
- [x] the command should use parameter -a and -p to add a user with the relative password
- [x] add more parameters to remove or modify users
- [x] add a salt unique to each user to compute hash
- [x] add hash repetition

**Comment by elenarogante** [comment]
I added two function to modify and delete usernames. I changed the check_function into a simpler one, adding quit(), so when calling the function, if the password or user is wrong the program stops.
commit 36720c245c520c4d792e049cae533794107ec930

**Comment by elenarogante** [comment]
issue solved in commit 8e170df64888aae50f2d48f8273cb98a01ae9f5e
