### ISSUE TITLE
code not working when using -e

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#18]
I noticed that, now that we have the user and password database, when adding the parameter -e, which is the one activating the API request, an error is returned:
[12/08/19]seed@VM:~/.../capitals$ userapp.py -ee -u massi -p 123 rome
ITALY
usage: userapp.py [-h] -p PASSWORD -u USERNAME [-v] [-r] [-c CHOOSECSV] [-e]
                  name
userapp.py: error: the following arguments are required: -p/--password, -u/--username
this is very strange indeed because -p and -u are there and the identical code without -e works

**Comment by swdevel-lab-hfarm** [comment]
Why do you call ```parse_args``` twice in your code? The second one produces the problem and I can't see any good reason for doing it

**Comment by saraweatherley** [comment]
we are using the second parse_args to get the name of the country from the function check_capital in the case the user uses -e and inputs the name of a capital. In this particular case, before running the function get_country_data (the one that uses the API) we need to retrieve the name of the country first, calling check_capital using the argument -r

**Comment by Leonardfonz** [comment]
we resolved eliminating "required=True" in username and password arguments and put a simple if statement to check if they are inserted
commit 480ebae3f81bd0f7f0c77a1f164001f4aff35932
