### ISSUE TITLE
make the repository a Python package

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#2]
inside the repository folder "capitals", create another folder called "capitalspackage". Inside this folder we should put:

- [x] the "__init__.py" file 

- [x] a valid licence 

- [x] a "setup.py" file. this isn't mandatory for the moment but it will be used to distribute the package

- [x] the Python file in which is defined the dictionary coutry-capital

- [x] the README.md file

in the folder "capitals", the only other file remaining should be "main.py", the file in which we try to use our package in practice.

**Comment by elenarogante** [comment]
solved in https://github.com/massimodalmonico/capitals/commit/eec54f2675910992376c4f7cb03d632d579e7641  
and https://github.com/massimodalmonico/capitals/commit/1a61f630e97d73d067a1c4bd8c9d9ce6bb75e75f
