### ISSUE TITLE
properly document the code!

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#4]
be sure to properly document all the bits of code that we are writing.
close this issue only at the end of each other step, after making sure everything's properly documented

**Comment by saraweatherley** [comment]
issue solved in 
https://github.com/massimodalmonico/capitals/commit/0fa102607e8741b403f1a2ba68c90469ae99d21c

**Comment by saraweatherley** [comment]
done in 58cbdf75a8ee13edc6ae1763f087c30f950e9510
