### ISSUE TITLE
add input to the code

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#5]
use "sys.argv"  to implement the possibility for the user to enter the name of a capital/coutry as the argument of the methods of the package. 
leave the "main.py" file as it is, with stardand entries, and make another file called "sisargv.py" to resolve this issue.

**Comment by AdaMalve** [comment]
Resolved in https://github.com/massimodalmonico/capitals/commit/87f005482ce1f1bd776ec00989b03411c4295492
