### ISSUE TITLE
substitute sys.argv with argparse for better input validation

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#8]
in the useapp.py file, we are currently use sys.argv to get input from user. it is better to use argparse, that allows input validation, which is an important feature of computer security.
in order to do so, we also have to change the methods contained in checks.py and move the output messages in userapp.py.

add at least one positional argument and one optional argument.

**Comment by saraweatherley** [comment]
solved in commit https://github.com/massimodalmonico/capitals/commit/8620b4b76c4593f32d921a0337e16eedc722c969
i deleted the main.py file because it's not used anymore (and doens't work anymore since I upgraded the checks functions)
