### ISSUE TITLE
substitute dictionary in checks.py file with file .csv

### ISSUE THREAD

**Issue by massimodalmonico** [massimodalmonico/capitals#9]
create a .csv file having the same entries of the dictionary in checks.py in order to use that from now on. include the .csv file in the repository, and eliminate the dictionary from checks.py.
do this before issue #8 so when we do that we use the csv file direcly. for the moment don't modify the code in checks.py for the same reason: it will be modified when adding the parser

**Comment by Leonardfonz** [comment]
solved in commit 58db7cb (see above)
